movie1project/movie1app/urls.py
from .import views
from django.urls import path
app_name='movie1app'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie1project/movie1project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie1app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie1project/movie1app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')


    def __str__(self):
        return self.name

movie1project/movie1app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie1project/movie1app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from . models import Movie
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add(request):
    if request.method=="POST":

        name=request.POST.get('name',)
        desc= request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method == "POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie1project/templates/add.html
{% extends 'base.html' %}
{% block body %}
<style>
.container{

  position: absolute;
  top: 20%;
  left:35%;
  }

</style>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <form method="POST" class="p-3 shadow" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="form-group">
                    <center><h5>Add a new Movie</h5></center>
                        <input type="text" name="name" placeholder="Enter your movie name"><br><br>
                </div>
                <div class="form-group">
                            <input type="text" name="desc" placeholder="Enter the movie description"><br><br>
                </div>
                <div class="form-group">
                            <input type="text" name="year" placeholder="Enter the movie year"><br><br>
                </div>
                <div class="form-group">
                            <input type="file" name="img"><br><br>
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
    </div>
</div>

{% endblock %}

movie1project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie1project/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" >
    {% csrf_token %}
    <h5>Are you want to delete this movie?</h5><br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="submit">
</form>
{% endblock %}

movie1project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container"><br>
    <div class="row">
        <div class="col-md-4">
            <img src ="{{movie.img.url}}" width="250" height="300">
        </div>
        <div class="col-md-6">
            <h4>{{movie.name}}</h4>
            <h5>{{movie.desc}}</h5>
            <h5>{{movie.year}}</h5>
        <a class="btn btn-warning" href="{% url 'movie1app:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movie1app:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

movie1project/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movie1project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container"><br>
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"  width="300px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movie1app:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
            </div><br>
        </div>
        {% endfor %}

    </div>
    <br>
        <center><a class="btn btn-primary" href="{% url 'movie1app:add'  %}">Add a new Movie</a></center><br>

</div>

{% endblock %}